spring.application.name=app-exception-logs
spring.datasource.url=jdbc:mysql://localhost:3306/bancodb?useSSL=false
spring.datasource.username=root
spring.datasource.password=admin2024

logging.level.root=INFO
logging.level.pe.edu.idat.app-exception-logs=DEBUG
logging.file.name=logs/retiro-app.log